Mobile version skeleton branch created
ZahraArshia/microverse-project1 pull request #1
Opened 2022-01-05 15:12 UTC by ZahraArshia

- html file added
- CSS file added 
- ReadMe updated

2022-01-05 16:14 UTC, micheaol requested changes
Hi @ZahraArshia, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!


## Required Changes ♻️

- _Check the comments under the review._
- Please ensure Linter is set up correctly for this repository. A linter is a tool that analyzes your source code to flag programming errors, bugs, stylistic errors, and suspicious constructs(source: [Wikipedia](https://en.wikipedia.org/wiki/Lint_(software))).

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-01-05 16:14 UTC, micheaol commented on index.html
> +                I’m Mariane Glad to see you!
Please stick to the design as much as possible (e.g. font, colors, images, tests, margins) using the [templates in Figma](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=0%3A1).
Please ensure to customize the content.

### Figma design:
![figma](https://user-images.githubusercontent.com/10332499/148245762-ea9d1bf1-b6ac-4ac5-b8c3-9e6b38e07384.PNG)

### Your Design:
![your-design](https://user-images.githubusercontent.com/10332499/148249917-b59c3764-170e-46d5-ab04-8cff2e3b344a.PNG)

2022-01-05 16:14 UTC, micheaol commented on styles.css
> +}
Your headline section should use flex In order to lay out the elements

2022-01-05 16:14 UTC, micheaol commented on index.html
> +            </section>
I will suggest you use 'div' if you need to have another division in a section instead of using 'section' in a 'section'. Section tag grouped the generic block of related contents. The main advantage of the section tag is, it is a semantic element, which describes its meaning to both browser and other developers.

2022-01-05 16:14 UTC, micheaol commented on index.html
> +                <img src="social-media-icons.png" alt="social media icons">
Please Implement the button interactions (enable, hover, etc.) for your social media icons.

2022-01-06 10:20 UTC, ZahraArshia commented
Hello
- appearance of the formed is changed based on template
- README updated to be more similar to template 
- screenshot of the project updated

2022-01-06 12:12 UTC, enkog requested changes
Hi @ZahraArshia 👋 , 

Great work 👍 on making the changes requested by the previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Required Changes ♻️
_Check the comments under the review._

- [ ] As part of the project requirement, I suggest you use the [HTML&CSS linter](https://github.com/microverseinc/linters-config/tree/master/html-css) for this project. You are currently using the one for `HTML/CSS and JavaScript` and because you do not have a .js file, the `Eslint` is failing. It would be nice to use this [link](https://github.com/microverseinc/linters-config/tree/master/html-css) to enable you setup the appropriate linter for this project.
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

- [ ]  [OPTIONAL] I suggest you move the images into an image folder to enable you have a clean code and to have a one-stop for all images.

- [ ] [OPTIONAL] Please update the live demo link on your README.md file. You can generate a live demo link to enable you and others see the page on the browser by visiting  [ https://raw.githack.com/](https://raw.githack.com/) and pasting the link address of your index.html file there.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-01-06 12:12 UTC, enkog commented on index.html
> +        </section>
- [ ]  [OPTIONAL] I suggest you remove these lines of code as they are not part of the design but indicate a mobile version of the design.

2022-01-06 19:13 UTC, ZahraArshia commented
Hello and thanks for reviewing
- ESLint removed
- images are placed in a folder now
- the README file updated to have a live demo link
- the section related to mobile status bar removed

2022-01-06 21:02 UTC, medaminedev66 reviewed
# Hi @ZahraArshia, 

### Status: Approved ✔️

:+1: You have implemented all the suggestions. Well Done.

Your project is complete!  There are some optional changes I've suggested to you to make your project best, other than that nothing else to say.
Congratulations! 🎉 


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

**You may close this Pull Request and merge the changes**

Cheers and Happy coding!👏👏👏
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Amine Snahi_**

------

_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project(check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-01-06 21:02 UTC, medaminedev66 commented on index.html
> +                </div>
[OPTIONAL]
- Please consider using a `ul` tag to wrap all the social icons and use `li` tag to wrap each of the social icons instead of a `div` tag. This is because the social icons are unordered lists and therefore should be wrapped with a `ul` and `li` tag and also to improve the code structure.

2022-01-06 21:02 UTC, medaminedev66 commented on index.html
> +            </div>
[Optional]
- It would be better to use `p` tag for this text to improve our structure and semantics.

2022-01-06 21:02 UTC, medaminedev66 commented on index.html
> +                <br> Glad to see you!
[Optional ]
- It would be better to use `h1` tag for the main title and `h2` tag for the subtitle to improve our structure and semantics.

2022-01-06 21:02 UTC, medaminedev66 commented on styles.css
> +}
[OPTIONAL]
- It would be better to remove the margin from the left and the top of your page so your design matches the Figma design. 
<img width="304" alt="image" src="https://user-images.githubusercontent.com/77190203/148451101-5802b9da-500b-42e3-9c55-059d93be15b4.png">

2022-01-07 15:15 UTC, merged